# Generated by Django 4.0.5 on 2022-06-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepoleinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'male'), (0, 'female')], default=1),
        ),
    ]
